# Generated by Django 3.1.12 on 2025-11-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walet', '0005_installationbenefit_referralbenefit'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('transaction_id', models.BigIntegerField(blank=True, null=True)),
                ('opening_bal', models.DecimalField(decimal_places=2, max_digits=13)),
                ('credit_bal', models.DecimalField(decimal_places=2, max_digits=13)),
                ('debit_bal', models.DecimalField(decimal_places=2, max_digits=13)),
                ('closing_bal', models.DecimalField(decimal_places=2, max_digits=13)),
                ('transaction_type', models.CharField(max_length=155)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wallet_transaction',
            },
        ),
    ]
