# Generated by Django 3.1.12 on 2025-11-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0013_auto_20250926_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='refer_by',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
