# Generated by Django 3.1.12 on 2025-11-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0014_customuser_refer_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercoupon',
            name='coupon',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customercoupon',
            name='coupon_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customercoupon',
            name='coupon_value',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customercoupon',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customercoupon',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='customercoupon',
            name='occasion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
