# Generated by Django 3.1.12 on 2025-11-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0015_auto_20251110_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercoupon',
            name='minimum_purchase',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
