# Generated by Django 3.1.12 on 2025-09-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_referrallink_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrallink',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
