# Generated by Django 3.1.12 on 2025-11-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0010_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand_name',
            field=models.CharField(blank=True, default=None, max_length=155, null=True),
        ),
    ]
