# Generated by Django 3.1.12 on 2025-12-08 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0012_itemreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemHighlights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended', models.BooleanField(default=False)),
                ('popular_item', models.BooleanField(default=False)),
                ('deals_of_the_day', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu_management.item')),
            ],
        ),
    ]
