# Generated by Django 3.1.12 on 2025-12-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0013_itemhighlights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='image_path',
        ),
        migrations.AddField(
            model_name='itemimage',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='item_media/'),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
    ]
